# Generated by Django 2.2.13 on 2021-08-21 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20210821_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='publish_at',
            field=models.DateTimeField(blank=True, verbose_name='Время публикации'),
        ),
    ]
