# Generated by Django 2.2.13 on 2021-08-21 05:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20210821_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='photo_img',
            field=models.ImageField(blank=True, null=True, upload_to='photos', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='publish_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Время публикации'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='text',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='Текст'),
        ),
    ]
