# Generated by Django 2.2.13 on 2021-08-21 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_advert_moderate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advert',
            name='moderate',
        ),
    ]
