# Generated by Django 2.2.13 on 2021-08-21 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_remove_advert_moderate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advert',
            options={'permissions': [('moderator', 'Модератор')], 'verbose_name': 'Объявление', 'verbose_name_plural': 'Объявлении'},
        ),
    ]
