# Generated by Django 2.1.5 on 2020-10-12 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0019_comment_like_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentlike',
            options={'verbose_name': 'Лайк', 'verbose_name_plural': 'Лайки комментариев'},
        ),
        migrations.AlterField(
            model_name='commentlike',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='webapp.Comment', verbose_name='Комментарий'),
        ),
    ]
